;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Skill.Active.Bigger.CoolTime",NewTagName="Skill.Active.Bigger.CoolDown")
+GameplayTagList=(Tag="Skill.Active.Bigger.CoolDown",DevComment="")
+GameplayTagList=(Tag="Skill.Active.Bouncy.CoolDown",DevComment="")
+GameplayTagList=(Tag="Skill.Active.Metalic.CoolDown",DevComment="")
+GameplayTagList=(Tag="Skill.Active.Spawn",DevComment="")
+GameplayTagList=(Tag="Skill.Active.Spawn.CoolDown",DevComment="")
+GameplayTagList=(Tag="Skill.Active.Strength",DevComment="")
+GameplayTagList=(Tag="Skill.Active.Strength.CoolDown",DevComment="")

